USE [master]
GO

/****** Object:  Database [Assignment05]    Script Date: 2/25/2016 3:12:05 PM ******/
CREATE DATABASE [Assignment05]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assignment05', FILENAME = N'C:\Users\usd33129\Assignment05.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Assignment05_log', FILENAME = N'C:\Users\usd33129\Assignment05_log.ldf' , SIZE = 784KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Assignment05] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assignment05].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Assignment05] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Assignment05] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Assignment05] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Assignment05] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Assignment05] SET ARITHABORT OFF 
GO

ALTER DATABASE [Assignment05] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Assignment05] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Assignment05] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Assignment05] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Assignment05] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Assignment05] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Assignment05] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Assignment05] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Assignment05] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Assignment05] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Assignment05] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Assignment05] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Assignment05] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Assignment05] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Assignment05] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Assignment05] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Assignment05] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Assignment05] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Assignment05] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Assignment05] SET  MULTI_USER 
GO

ALTER DATABASE [Assignment05] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Assignment05] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Assignment05] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Assignment05] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Assignment05] SET  READ_WRITE 
GO


