//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EntityFrameworkDemosModel", "fkOrdersToCustomers", "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EntityFrameworkDemosProcessor.Customer), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkDemosProcessor.Order), true)]
[assembly: EdmRelationshipAttribute("EntityFrameworkDemosModel", "fkOrderLineItemsToOrders", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EntityFrameworkDemosProcessor.Order), "OrderLineItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkDemosProcessor.OrderLineItem), true)]
[assembly: EdmRelationshipAttribute("EntityFrameworkDemosModel", "fkOrderLineItemsToProducts", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EntityFrameworkDemosProcessor.Product), "OrderLineItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EntityFrameworkDemosProcessor.OrderLineItem), true)]

#endregion

namespace EntityFrameworkDemosProcessor
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EntityFrameworkDemosEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EntityFrameworkDemosEntities object using the connection string found in the 'EntityFrameworkDemosEntities' section of the application configuration file.
        /// </summary>
        public EntityFrameworkDemosEntities() : base("name=EntityFrameworkDemosEntities", "EntityFrameworkDemosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntityFrameworkDemosEntities object.
        /// </summary>
        public EntityFrameworkDemosEntities(string connectionString) : base(connectionString, "EntityFrameworkDemosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntityFrameworkDemosEntities object.
        /// </summary>
        public EntityFrameworkDemosEntities(EntityConnection connection) : base(connection, "EntityFrameworkDemosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderLineItem> OrderLineItems
        {
            get
            {
                if ((_OrderLineItems == null))
                {
                    _OrderLineItems = base.CreateObjectSet<OrderLineItem>("OrderLineItems");
                }
                return _OrderLineItems;
            }
        }
        private ObjectSet<OrderLineItem> _OrderLineItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vCustomer> vCustomers
        {
            get
            {
                if ((_vCustomers == null))
                {
                    _vCustomers = base.CreateObjectSet<vCustomer>("vCustomers");
                }
                return _vCustomers;
            }
        }
        private ObjectSet<vCustomer> _vCustomers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vOrderLineItem> vOrderLineItems
        {
            get
            {
                if ((_vOrderLineItems == null))
                {
                    _vOrderLineItems = base.CreateObjectSet<vOrderLineItem>("vOrderLineItems");
                }
                return _vOrderLineItems;
            }
        }
        private ObjectSet<vOrderLineItem> _vOrderLineItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vOrder> vOrders
        {
            get
            {
                if ((_vOrders == null))
                {
                    _vOrders = base.CreateObjectSet<vOrder>("vOrders");
                }
                return _vOrders;
            }
        }
        private ObjectSet<vOrder> _vOrders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vProduct> vProducts
        {
            get
            {
                if ((_vProducts == null))
                {
                    _vProducts = base.CreateObjectSet<vProduct>("vProducts");
                }
                return _vProducts;
            }
        }
        private ObjectSet<vProduct> _vProducts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vRptOrdersByProduct> vRptOrdersByProducts
        {
            get
            {
                if ((_vRptOrdersByProducts == null))
                {
                    _vRptOrdersByProducts = base.CreateObjectSet<vRptOrdersByProduct>("vRptOrdersByProducts");
                }
                return _vRptOrdersByProducts;
            }
        }
        private ObjectSet<vRptOrdersByProduct> _vRptOrdersByProducts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderLineItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderLineItems(OrderLineItem orderLineItem)
        {
            base.AddObject("OrderLineItems", orderLineItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vCustomers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovCustomers(vCustomer vCustomer)
        {
            base.AddObject("vCustomers", vCustomer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vOrderLineItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovOrderLineItems(vOrderLineItem vOrderLineItem)
        {
            base.AddObject("vOrderLineItems", vOrderLineItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vOrders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovOrders(vOrder vOrder)
        {
            base.AddObject("vOrders", vOrder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vProducts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovProducts(vProduct vProduct)
        {
            base.AddObject("vProducts", vProduct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vRptOrdersByProducts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovRptOrdersByProducts(vRptOrdersByProduct vRptOrdersByProduct)
        {
            base.AddObject("vRptOrdersByProducts", vRptOrdersByProduct);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="customerID">No Metadata Documentation available.</param>
        public int pDelCustomer(Nullable<global::System.Int32> customerID)
        {
            ObjectParameter customerIDParameter;
            if (customerID.HasValue)
            {
                customerIDParameter = new ObjectParameter("CustomerID", customerID);
            }
            else
            {
                customerIDParameter = new ObjectParameter("CustomerID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("pDelCustomer", customerIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="customerID">No Metadata Documentation available.</param>
        /// <param name="customerName">No Metadata Documentation available.</param>
        public int pInsCustomer(Nullable<global::System.Int32> customerID, global::System.String customerName)
        {
            ObjectParameter customerIDParameter;
            if (customerID.HasValue)
            {
                customerIDParameter = new ObjectParameter("CustomerID", customerID);
            }
            else
            {
                customerIDParameter = new ObjectParameter("CustomerID", typeof(global::System.Int32));
            }
    
            ObjectParameter customerNameParameter;
            if (customerName != null)
            {
                customerNameParameter = new ObjectParameter("CustomerName", customerName);
            }
            else
            {
                customerNameParameter = new ObjectParameter("CustomerName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("pInsCustomer", customerIDParameter, customerNameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="customerID">No Metadata Documentation available.</param>
        /// <param name="customerName">No Metadata Documentation available.</param>
        public int pUpdateCustomer(Nullable<global::System.Int32> customerID, global::System.String customerName)
        {
            ObjectParameter customerIDParameter;
            if (customerID.HasValue)
            {
                customerIDParameter = new ObjectParameter("CustomerID", customerID);
            }
            else
            {
                customerIDParameter = new ObjectParameter("CustomerID", typeof(global::System.Int32));
            }
    
            ObjectParameter customerNameParameter;
            if (customerName != null)
            {
                customerNameParameter = new ObjectParameter("CustomerName", customerName);
            }
            else
            {
                customerNameParameter = new ObjectParameter("CustomerName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("pUpdateCustomer", customerIDParameter, customerNameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<pRptOrdersByProducts_Result> pRptOrdersByProducts()
        {
            return base.ExecuteFunction<pRptOrdersByProducts_Result>("pRptOrdersByProducts");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityFrameworkDemosModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        public static Customer CreateCustomer(global::System.Int32 customerID)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityFrameworkDemosModel", "fkOrdersToCustomers", "Orders")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("EntityFrameworkDemosModel.fkOrdersToCustomers", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("EntityFrameworkDemosModel.fkOrdersToCustomers", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityFrameworkDemosModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        public static Order CreateOrder(global::System.Int32 orderID)
        {
            Order order = new Order();
            order.OrderID = orderID;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CustomerId;
        partial void OnCustomerIdChanging(Nullable<global::System.Int32> value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrderDate;
        partial void OnOrderDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrderDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityFrameworkDemosModel", "fkOrdersToCustomers", "Customers")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("EntityFrameworkDemosModel.fkOrdersToCustomers", "Customers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("EntityFrameworkDemosModel.fkOrdersToCustomers", "Customers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("EntityFrameworkDemosModel.fkOrdersToCustomers", "Customers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("EntityFrameworkDemosModel.fkOrdersToCustomers", "Customers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityFrameworkDemosModel", "fkOrderLineItemsToOrders", "OrderLineItems")]
        public EntityCollection<OrderLineItem> OrderLineItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderLineItem>("EntityFrameworkDemosModel.fkOrderLineItemsToOrders", "OrderLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderLineItem>("EntityFrameworkDemosModel.fkOrderLineItemsToOrders", "OrderLineItems", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityFrameworkDemosModel", Name="OrderLineItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderLineItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderLineItem object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        public static OrderLineItem CreateOrderLineItem(global::System.Int32 orderID, global::System.Int32 productID)
        {
            OrderLineItem orderLineItem = new OrderLineItem();
            orderLineItem.OrderID = orderID;
            orderLineItem.ProductID = productID;
            return orderLineItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderLineItemID
        {
            get
            {
                return _OrderLineItemID;
            }
            set
            {
                OnOrderLineItemIDChanging(value);
                ReportPropertyChanging("OrderLineItemID");
                _OrderLineItemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderLineItemID");
                OnOrderLineItemIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderLineItemID;
        partial void OnOrderLineItemIDChanging(Nullable<global::System.Int32> value);
        partial void OnOrderLineItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderQty
        {
            get
            {
                return _OrderQty;
            }
            set
            {
                OnOrderQtyChanging(value);
                ReportPropertyChanging("OrderQty");
                _OrderQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderQty");
                OnOrderQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderQty;
        partial void OnOrderQtyChanging(Nullable<global::System.Int32> value);
        partial void OnOrderQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OrderSalesPrice
        {
            get
            {
                return _OrderSalesPrice;
            }
            set
            {
                OnOrderSalesPriceChanging(value);
                ReportPropertyChanging("OrderSalesPrice");
                _OrderSalesPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderSalesPrice");
                OnOrderSalesPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _OrderSalesPrice;
        partial void OnOrderSalesPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnOrderSalesPriceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityFrameworkDemosModel", "fkOrderLineItemsToOrders", "Orders")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("EntityFrameworkDemosModel.fkOrderLineItemsToOrders", "Orders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("EntityFrameworkDemosModel.fkOrderLineItemsToOrders", "Orders").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("EntityFrameworkDemosModel.fkOrderLineItemsToOrders", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("EntityFrameworkDemosModel.fkOrderLineItemsToOrders", "Orders", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityFrameworkDemosModel", "fkOrderLineItemsToProducts", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("EntityFrameworkDemosModel.fkOrderLineItemsToProducts", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("EntityFrameworkDemosModel.fkOrderLineItemsToProducts", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("EntityFrameworkDemosModel.fkOrderLineItemsToProducts", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("EntityFrameworkDemosModel.fkOrderLineItemsToProducts", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityFrameworkDemosModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of the ProductID property.</param>
        public static Product CreateProduct(global::System.Int32 productID)
        {
            Product product = new Product();
            product.ProductID = productID;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ProductPrice
        {
            get
            {
                return _ProductPrice;
            }
            set
            {
                OnProductPriceChanging(value);
                ReportPropertyChanging("ProductPrice");
                _ProductPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductPrice");
                OnProductPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ProductPrice;
        partial void OnProductPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnProductPriceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EntityFrameworkDemosModel", "fkOrderLineItemsToProducts", "OrderLineItems")]
        public EntityCollection<OrderLineItem> OrderLineItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderLineItem>("EntityFrameworkDemosModel.fkOrderLineItemsToProducts", "OrderLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderLineItem>("EntityFrameworkDemosModel.fkOrderLineItemsToProducts", "OrderLineItems", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityFrameworkDemosModel", Name="vCustomer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vCustomer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vCustomer object.
        /// </summary>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        public static vCustomer CreatevCustomer(global::System.Int32 customerID)
        {
            vCustomer vCustomer = new vCustomer();
            vCustomer.CustomerID = customerID;
            return vCustomer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityFrameworkDemosModel", Name="vOrder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vOrder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vOrder object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        public static vOrder CreatevOrder(global::System.Int32 orderID)
        {
            vOrder vOrder = new vOrder();
            vOrder.OrderID = orderID;
            return vOrder;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CustomerId;
        partial void OnCustomerIdChanging(Nullable<global::System.Int32> value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrderDate;
        partial void OnOrderDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrderDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityFrameworkDemosModel", Name="vOrderLineItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vOrderLineItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vOrderLineItem object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        public static vOrderLineItem CreatevOrderLineItem(global::System.Int32 orderID, global::System.Int32 productID)
        {
            vOrderLineItem vOrderLineItem = new vOrderLineItem();
            vOrderLineItem.OrderID = orderID;
            vOrderLineItem.ProductID = productID;
            return vOrderLineItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderLineItemID
        {
            get
            {
                return _OrderLineItemID;
            }
            set
            {
                OnOrderLineItemIDChanging(value);
                ReportPropertyChanging("OrderLineItemID");
                _OrderLineItemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderLineItemID");
                OnOrderLineItemIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderLineItemID;
        partial void OnOrderLineItemIDChanging(Nullable<global::System.Int32> value);
        partial void OnOrderLineItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderQty
        {
            get
            {
                return _OrderQty;
            }
            set
            {
                OnOrderQtyChanging(value);
                ReportPropertyChanging("OrderQty");
                _OrderQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderQty");
                OnOrderQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderQty;
        partial void OnOrderQtyChanging(Nullable<global::System.Int32> value);
        partial void OnOrderQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OrderSalesPrice
        {
            get
            {
                return _OrderSalesPrice;
            }
            set
            {
                OnOrderSalesPriceChanging(value);
                ReportPropertyChanging("OrderSalesPrice");
                _OrderSalesPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderSalesPrice");
                OnOrderSalesPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _OrderSalesPrice;
        partial void OnOrderSalesPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnOrderSalesPriceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityFrameworkDemosModel", Name="vProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vProduct object.
        /// </summary>
        /// <param name="productID">Initial value of the ProductID property.</param>
        public static vProduct CreatevProduct(global::System.Int32 productID)
        {
            vProduct vProduct = new vProduct();
            vProduct.ProductID = productID;
            return vProduct;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ProductPrice
        {
            get
            {
                return _ProductPrice;
            }
            set
            {
                OnProductPriceChanging(value);
                ReportPropertyChanging("ProductPrice");
                _ProductPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductPrice");
                OnProductPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ProductPrice;
        partial void OnProductPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnProductPriceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EntityFrameworkDemosModel", Name="vRptOrdersByProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vRptOrdersByProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vRptOrdersByProduct object.
        /// </summary>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        public static vRptOrdersByProduct CreatevRptOrdersByProduct(global::System.Int32 orderId)
        {
            vRptOrdersByProduct vRptOrdersByProduct = new vRptOrdersByProduct();
            vRptOrdersByProduct.OrderId = orderId;
            return vRptOrdersByProduct;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.Int32 _OrderId;
        partial void OnOrderIdChanging(global::System.Int32 value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrderDate;
        partial void OnOrderDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderQty
        {
            get
            {
                return _OrderQty;
            }
            set
            {
                OnOrderQtyChanging(value);
                ReportPropertyChanging("OrderQty");
                _OrderQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderQty");
                OnOrderQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderQty;
        partial void OnOrderQtyChanging(Nullable<global::System.Int32> value);
        partial void OnOrderQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OrderSalesPrice
        {
            get
            {
                return _OrderSalesPrice;
            }
            set
            {
                OnOrderSalesPriceChanging(value);
                ReportPropertyChanging("OrderSalesPrice");
                _OrderSalesPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderSalesPrice");
                OnOrderSalesPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _OrderSalesPrice;
        partial void OnOrderSalesPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnOrderSalesPriceChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="EntityFrameworkDemosModel", Name="pRptOrdersByProducts_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class pRptOrdersByProducts_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pRptOrdersByProducts_Result object.
        /// </summary>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        public static pRptOrdersByProducts_Result CreatepRptOrdersByProducts_Result(global::System.Int32 orderId)
        {
            pRptOrdersByProducts_Result pRptOrdersByProducts_Result = new pRptOrdersByProducts_Result();
            pRptOrdersByProducts_Result.OrderId = orderId;
            return pRptOrdersByProducts_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                OnOrderIdChanging(value);
                ReportPropertyChanging("OrderId");
                _OrderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderId");
                OnOrderIdChanged();
            }
        }
        private global::System.Int32 _OrderId;
        partial void OnOrderIdChanging(global::System.Int32 value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrderDate;
        partial void OnOrderDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderQty
        {
            get
            {
                return _OrderQty;
            }
            set
            {
                OnOrderQtyChanging(value);
                ReportPropertyChanging("OrderQty");
                _OrderQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderQty");
                OnOrderQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderQty;
        partial void OnOrderQtyChanging(Nullable<global::System.Int32> value);
        partial void OnOrderQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OrderSalesPrice
        {
            get
            {
                return _OrderSalesPrice;
            }
            set
            {
                OnOrderSalesPriceChanging(value);
                ReportPropertyChanging("OrderSalesPrice");
                _OrderSalesPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderSalesPrice");
                OnOrderSalesPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _OrderSalesPrice;
        partial void OnOrderSalesPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnOrderSalesPriceChanged();

        #endregion
    }

    #endregion
    
}
